packages:
  - 'packages/*'

allowBuilds:
  esbuild: true
  workerd: true

catalog:
  typescript: ^5.9.2
  vitest: ^4.1.0

minimumReleaseAgeExclude:
  - '@tanstack/react-router@1.170.25'
  - '@tanstack/router-core@1.171.21'
  - '@tanstack/router-generator@1.167.27'
  - '@tanstack/router-plugin@1.168.29'
  - lucide-react@1.31.0
