/// <reference types="@cloudflare/workers-types" />

export async function applyMigrations(
  db: D1Database,
  statements: string[]
): Promise<void> {
  for (const stmt of statements) {
    await db.exec(stmt);
  }
}

export const MIGRATION_STATEMENTS: string[] = [
  `CREATE TABLE IF NOT EXISTS auth_token (id text PRIMARY KEY NOT NULL, email text NOT NULL, token text NOT NULL, expires_at text NOT NULL, used_at text, two_factor_code text, two_factor_expires_at text, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS organization (id text PRIMARY KEY NOT NULL, name text NOT NULL, type text NOT NULL, parent_id text, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS congregation (id text PRIMARY KEY NOT NULL, name text NOT NULL, type text NOT NULL, parent_id text, parent_type text, organization_id text REFERENCES organization(id), timezone text DEFAULT 'UTC' NOT NULL, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS person (id text PRIMARY KEY NOT NULL, congregation_id text NOT NULL REFERENCES congregation(id), first_name text NOT NULL, last_name text NOT NULL, email text, phone text, address text, is_member integer DEFAULT false, created_at text NOT NULL, updated_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS department (id text PRIMARY KEY NOT NULL, congregation_id text NOT NULL REFERENCES congregation(id), name text NOT NULL, type text NOT NULL, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS role (id text PRIMARY KEY NOT NULL, person_id text REFERENCES person(id), congregation_id text NOT NULL REFERENCES congregation(id), role_type text NOT NULL, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS "user" (id text PRIMARY KEY NOT NULL, email text NOT NULL, person_id text REFERENCES person(id), congregation_id text REFERENCES congregation(id), created_at text NOT NULL)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS user_email_unique ON "user" (email)`,
  `CREATE TABLE IF NOT EXISTS receipt (id text PRIMARY KEY NOT NULL, congregation_id text NOT NULL REFERENCES congregation(id), member_id text NOT NULL REFERENCES person(id), amount integer NOT NULL, fund_split text NOT NULL, image_key text, status text NOT NULL DEFAULT 'pending', verified_by_id text REFERENCES person(id), verified_at text, rejection_note text, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS board_meeting (id text PRIMARY KEY NOT NULL, congregation_id text NOT NULL REFERENCES congregation(id), date text NOT NULL, agenda text, status text NOT NULL DEFAULT 'draft', created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS board_minute (id text PRIMARY KEY NOT NULL, meeting_id text NOT NULL REFERENCES board_meeting(id), content text NOT NULL, revision_number integer NOT NULL DEFAULT 1, author_id text NOT NULL REFERENCES person(id), created_at text NOT NULL, updated_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS board_decision (id text PRIMARY KEY NOT NULL, meeting_id text NOT NULL REFERENCES board_meeting(id), number integer NOT NULL, title text NOT NULL, description text, mover_id text REFERENCES person(id), seconder_id text REFERENCES person(id), vote_outcome text, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS duty_slot (id text PRIMARY KEY NOT NULL, congregation_id text NOT NULL REFERENCES congregation(id), date text NOT NULL, role text NOT NULL, volunteer_id text REFERENCES person(id), status text NOT NULL DEFAULT 'open', created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS safety_clearance (id text PRIMARY KEY NOT NULL, volunteer_id text NOT NULL REFERENCES person(id), congregation_id text NOT NULL REFERENCES congregation(id), type text NOT NULL, issued_date text NOT NULL, expiry_date text NOT NULL, certificate_key text, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS expense (id text PRIMARY KEY NOT NULL, congregation_id text NOT NULL REFERENCES congregation(id), amount integer NOT NULL, description text NOT NULL, category text NOT NULL, receipt_id text REFERENCES receipt(id), board_decision_id text REFERENCES board_decision(id), created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS pathfinder_progress (id text PRIMARY KEY NOT NULL, member_id text NOT NULL REFERENCES person(id), class_name text NOT NULL, club_type text NOT NULL, status text NOT NULL DEFAULT 'in_progress', completed_at text, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS pathfinder_honor (id text PRIMARY KEY NOT NULL, member_id text NOT NULL REFERENCES person(id), name text NOT NULL, category text NOT NULL, earned_at text NOT NULL, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS sabbath_school_class (id text PRIMARY KEY NOT NULL, congregation_id text NOT NULL REFERENCES congregation(id), division text NOT NULL, name text NOT NULL, teacher_id text REFERENCES person(id), created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS sabbath_school_attendance (id text PRIMARY KEY NOT NULL, class_id text NOT NULL REFERENCES sabbath_school_class(id), date text NOT NULL, member_id text NOT NULL REFERENCES person(id), present integer NOT NULL, notes text, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS welfare_case (id text PRIMARY KEY NOT NULL, congregation_id text NOT NULL REFERENCES congregation(id), person_id text REFERENCES person(id), assistance_type text NOT NULL, description text NOT NULL, value integer, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS pantry_item (id text PRIMARY KEY NOT NULL, congregation_id text NOT NULL REFERENCES congregation(id), name text NOT NULL, quantity integer NOT NULL, unit text NOT NULL, updated_at text NOT NULL, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS health_event (id text PRIMARY KEY NOT NULL, congregation_id text NOT NULL REFERENCES congregation(id), name text NOT NULL, date text NOT NULL, type text NOT NULL, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS health_contact (id text PRIMARY KEY NOT NULL, event_id text NOT NULL REFERENCES health_event(id), congregation_id text NOT NULL REFERENCES congregation(id), name text NOT NULL, phone text, email text, interests text, follow_up_status text NOT NULL DEFAULT 'new', created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS household (id text PRIMARY KEY NOT NULL, congregation_id text NOT NULL REFERENCES congregation(id), name text NOT NULL, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS household_member (id text PRIMARY KEY NOT NULL, household_id text NOT NULL REFERENCES household(id), person_id text NOT NULL REFERENCES person(id), relationship text NOT NULL, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS candidacy (id text PRIMARY KEY NOT NULL, person_id text NOT NULL REFERENCES person(id), congregation_id text NOT NULL REFERENCES congregation(id), stage text NOT NULL, start_date text NOT NULL, decision_date text, decision_type text, officiating_pastor_id text REFERENCES person(id), created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS communion_service (id text PRIMARY KEY NOT NULL, congregation_id text NOT NULL REFERENCES congregation(id), date text NOT NULL, status text NOT NULL DEFAULT 'planned', created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS communion_room (id text PRIMARY KEY NOT NULL, service_id text NOT NULL REFERENCES communion_service(id), name text NOT NULL, gender text NOT NULL, volunteer_ids text)`,
  `CREATE TABLE IF NOT EXISTS communion_inventory (id text PRIMARY KEY NOT NULL, service_id text NOT NULL REFERENCES communion_service(id), item text NOT NULL, quantity integer NOT NULL, unit text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS av_order_of_service (id text PRIMARY KEY NOT NULL, congregation_id text NOT NULL REFERENCES congregation(id), date text NOT NULL, items text NOT NULL, updated_at text NOT NULL, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS district (id text PRIMARY KEY NOT NULL, name text NOT NULL, organization_id text REFERENCES organization(id), created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS district_congregation (id text PRIMARY KEY NOT NULL, district_id text NOT NULL REFERENCES district(id), congregation_id text NOT NULL REFERENCES congregation(id))`,
  `CREATE TABLE IF NOT EXISTS preaching_rotation (id text PRIMARY KEY NOT NULL, congregation_id text NOT NULL REFERENCES congregation(id), date text NOT NULL, preacher_id text NOT NULL REFERENCES person(id), topic text, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS pastoral_visit (id text PRIMARY KEY NOT NULL, household_id text REFERENCES household(id), pastor_id text NOT NULL REFERENCES person(id), congregation_id text NOT NULL REFERENCES congregation(id), date text NOT NULL, purpose text, notes text, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS facility_booking (id text PRIMARY KEY NOT NULL, congregation_id text NOT NULL REFERENCES congregation(id), date text NOT NULL, time_start text NOT NULL, time_end text NOT NULL, purpose text NOT NULL, requester_id text REFERENCES person(id), status text NOT NULL DEFAULT 'pending', created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS congregation_asset (id text PRIMARY KEY NOT NULL, congregation_id text NOT NULL REFERENCES congregation(id), type text NOT NULL, description text, status text NOT NULL DEFAULT 'operational', updated_at text NOT NULL, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS transfer_request (id text PRIMARY KEY NOT NULL, member_id text NOT NULL REFERENCES person(id), from_congregation_id text NOT NULL REFERENCES congregation(id), to_congregation_id text NOT NULL REFERENCES congregation(id), status text NOT NULL DEFAULT 'requested', requested_by_id text REFERENCES person(id), approved_by_id text REFERENCES person(id), received_by_id text REFERENCES person(id), created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS nominating_session (id text PRIMARY KEY NOT NULL, congregation_id text NOT NULL REFERENCES congregation(id), year integer NOT NULL, status text NOT NULL DEFAULT 'open', opened_by_id text REFERENCES person(id), created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS nominating_role (id text PRIMARY KEY NOT NULL, session_id text NOT NULL REFERENCES nominating_session(id), role_type text NOT NULL, status text NOT NULL DEFAULT 'open', created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS nominating_candidate (id text PRIMARY KEY NOT NULL, role_id text NOT NULL REFERENCES nominating_role(id), person_id text NOT NULL REFERENCES person(id), nominated_by_id text REFERENCES person(id), status text NOT NULL DEFAULT 'nominated', created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS discipline_case (id text PRIMARY KEY NOT NULL, congregation_id text NOT NULL REFERENCES congregation(id), person_id text NOT NULL REFERENCES person(id), case_type text NOT NULL, status text NOT NULL DEFAULT 'active', description text NOT NULL, resolution text, decided_by_id text REFERENCES person(id), decided_at text, board_meeting_id text REFERENCES board_meeting(id), created_at text NOT NULL, updated_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS audit_log (id text PRIMARY KEY NOT NULL, congregation_id text NOT NULL REFERENCES congregation(id), actor_id text NOT NULL REFERENCES person(id), action text NOT NULL, resource_type text NOT NULL, resource_id text, details text, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS nominating_ballot (id text PRIMARY KEY NOT NULL, session_id text NOT NULL REFERENCES nominating_session(id), role_id text NOT NULL REFERENCES nominating_role(id), candidate_id text REFERENCES nominating_candidate(id), voter_id text NOT NULL REFERENCES person(id), encrypted_vote text NOT NULL, created_at text NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS bank_account (id text PRIMARY KEY NOT NULL, congregation_id text NOT NULL REFERENCES congregation(id), bank_name text NOT NULL, account_name text NOT NULL, account_number text NOT NULL, created_at text NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS auth_token_token_idx ON auth_token(token)`,
  `CREATE INDEX IF NOT EXISTS auth_token_email_idx ON auth_token(email)`,
  `CREATE INDEX IF NOT EXISTS person_congregation_idx ON person(congregation_id)`,
  `CREATE INDEX IF NOT EXISTS person_email_idx ON person(email)`,
  `CREATE INDEX IF NOT EXISTS role_person_idx ON role(person_id)`,
  `CREATE INDEX IF NOT EXISTS role_congregation_idx ON role(congregation_id)`,
  `CREATE INDEX IF NOT EXISTS receipt_congregation_idx ON receipt(congregation_id)`,
  `CREATE INDEX IF NOT EXISTS receipt_status_idx ON receipt(status)`,
  `CREATE INDEX IF NOT EXISTS duty_slot_congregation_date_idx ON duty_slot(congregation_id, date)`,
  `CREATE INDEX IF NOT EXISTS board_meeting_congregation_idx ON board_meeting(congregation_id)`,
  `CREATE INDEX IF NOT EXISTS board_decision_meeting_idx ON board_decision(meeting_id)`,
  `CREATE INDEX IF NOT EXISTS expense_congregation_idx ON expense(congregation_id)`,
  `CREATE INDEX IF NOT EXISTS transfer_from_congregation_idx ON transfer_request(from_congregation_id)`,
  `CREATE INDEX IF NOT EXISTS transfer_to_congregation_idx ON transfer_request(to_congregation_id)`,
  `CREATE INDEX IF NOT EXISTS candidacy_congregation_idx ON candidacy(congregation_id)`,
  `CREATE INDEX IF NOT EXISTS discipline_case_congregation_idx ON discipline_case(congregation_id)`,
  `CREATE INDEX IF NOT EXISTS audit_log_congregation_idx ON audit_log(congregation_id)`,
  `CREATE INDEX IF NOT EXISTS audit_log_actor_idx ON audit_log(actor_id)`,
  `CREATE INDEX IF NOT EXISTS nominating_ballot_session_idx ON nominating_ballot(session_id)`,
];
