/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MembersIndexRouteImport } from './routes/members/index'
import { Route as MembersAddRouteImport } from './routes/members/add'
import { Route as MembersMemberIdRouteImport } from './routes/members/$memberId'
import { Route as MembersMemberIdEditRouteImport } from './routes/members/$memberId.edit'
import { Route as ChurchImportRouteImport } from './routes/church/import'
import { Route as ChurchRegisterRouteImport } from './routes/church/register'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersAddRoute = MembersAddRouteImport.update({
  id: '/members/add',
  path: '/members/add',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersMemberIdRoute = MembersMemberIdRouteImport.update({
  id: '/members/$memberId',
  path: '/members/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersMemberIdEditRoute = MembersMemberIdEditRouteImport.update({
  id: '/members/$memberId/edit',
  path: '/members/$memberId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ChurchImportRoute = ChurchImportRouteImport.update({
  id: '/church/import',
  path: '/church/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ChurchRegisterRoute = ChurchRegisterRouteImport.update({
  id: '/church/register',
  path: '/church/register',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersIndexRoute
  '/members/add': typeof MembersAddRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/members/$memberId/edit': typeof MembersMemberIdEditRoute
  '/church/import': typeof ChurchImportRoute
  '/church/register': typeof ChurchRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersIndexRoute
  '/members/add': typeof MembersAddRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/members/$memberId/edit': typeof MembersMemberIdEditRoute
  '/church/import': typeof ChurchImportRoute
  '/church/register': typeof ChurchRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersIndexRoute
  '/members/add': typeof MembersAddRoute
  '/members/$memberId': typeof MembersMemberIdRoute
  '/members/$memberId/edit': typeof MembersMemberIdEditRoute
  '/church/import': typeof ChurchImportRoute
  '/church/register': typeof ChurchRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/members' | '/members/add' | '/members/$memberId' | '/members/$memberId/edit' | '/church/import' | '/church/register'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/members' | '/members/add' | '/members/$memberId' | '/members/$memberId/edit' | '/church/import' | '/church/register'
  id: '__root__' | '/' | '/login' | '/members' | '/members/add' | '/members/$memberId' | '/members/$memberId/edit' | '/church/import' | '/church/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MembersIndexRoute: typeof MembersIndexRoute
  MembersAddRoute: typeof MembersAddRoute
  MembersMemberIdRoute: typeof MembersMemberIdRoute
  MembersMemberIdEditRoute: typeof MembersMemberIdEditRoute
  ChurchImportRoute: typeof ChurchImportRoute
  ChurchRegisterRoute: typeof ChurchRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/add': {
      id: '/members/add'
      path: '/members/add'
      fullPath: '/members/add'
      preLoaderRoute: typeof MembersAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/$memberId': {
      id: '/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof MembersMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/$memberId/edit': {
      id: '/members/$memberId/edit'
      path: '/members/$memberId/edit'
      fullPath: '/members/$memberId/edit'
      preLoaderRoute: typeof MembersMemberIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/church/import': {
      id: '/church/import'
      path: '/church/import'
      fullPath: '/church/import'
      preLoaderRoute: typeof ChurchImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/church/register': {
      id: '/church/register'
      path: '/church/register'
      fullPath: '/church/register'
      preLoaderRoute: typeof ChurchRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MembersIndexRoute: MembersIndexRoute,
  MembersAddRoute: MembersAddRoute,
  MembersMemberIdRoute: MembersMemberIdRoute,
  MembersMemberIdEditRoute: MembersMemberIdEditRoute,
  ChurchImportRoute: ChurchImportRoute,
  ChurchRegisterRoute: ChurchRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
