import type { D1Migration } from '@cloudflare/vitest-pool-workers'

// Merges into the Cloudflare.Env interface generated by `wrangler types`
// (worker-configuration.d.ts) — test-only, not a real Worker binding.
// `declare global` is required here (not a bare `declare namespace`)
// because this file has a top-level import, making it a module rather
// than an ambient script, so the namespace wouldn't otherwise merge
// with the global one from worker-configuration.d.ts.
declare global {
  namespace Cloudflare {
    interface Env {
      TEST_MIGRATIONS: D1Migration[]
    }
  }
}
